### ISSUE TITLE
팀 편성 공지

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2019-Spring#18]
팀1: 김강수, 김휘겸, 이수빈
팀2: 송창훈, 이영민, 조성환
팀3: 김도혁, 윤석빈, 이의현

위와 같이 팀을 편성하게 되었으니 확인 바랍니다.

**Comment by sangkilc** [comment]
We have created a repository for each team.

Team1: 2019s-team2
Team2: 2019s-team1
Team3: 2019s-team3

Make sure you can access the above repository. Team 1 and 2 have a wrong repo name but don't worry, just ignore it for now :smile:

**Comment by sangkilc** [comment]
다음주 발표까지 각 팀별로 팀 이름과 팀 리더를 정해서 오시기 바랍니다.
