### ISSUE TITLE
숙제 1 질문

### ISSUE THREAD

**Issue by Hwi-gyeom** [KAIST-IS521/2019-Spring#2]
숙제 1 진행하던 도중 질문이 생겨서 질문드립니다.

![default](https://user-images.githubusercontent.com/48077155/53883729-1f227980-405d-11e9-9ef2-fe87dffcd839.PNG)

첨부한 이미지와 같이 한 데이터가 두 행에 걸쳐서 표현되는 경우도 있다고 하는데,

이런 경우 숙제의 Column 계산을 할 때 어떻게 간주해야 한다는 지시사항이 없어서 질문드립니다.

저렇게 표현되는 데이터가 목표한 column 의 어느 쪽에도 속하지 않았다면 그냥 두 셀로 생각하면

될거같은데,

두 column 중 하나가 목표한 column이라면 두 부분을 모두 출력하는 것이 좋을까요 해당하는 column만 출력하는 것이 좋을까요?

감사합니다. 답변기다리겠습니다.

**Comment by sangkilc** [comment]
위의 예제에서는 따옴표 안의 CRLF는 개행으로 간주되는것이 아니라 따옴표 전체가 하나의 셀로 간주되기 때문에 총 2 줄이 있는 CSV가 됩니다. 따라서 두 번째 컬럼을 프린트하면
```
"b CRLF
bb"
yyy
```
가 되야 합니다.

**Comment by sangkilc** [comment]
위에 따옴표가 없어야 정상적 출력입니다.
