### ISSUE TITLE
About Score & Presentation slide

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2019-Spring#25]
Hi all,

We just uploaded a grade of the presentation done on yesterday. You can check it on your private repository.

One more thing to do, one of your team members should upload the slides on [KLMS](http://klms.kaist.ac.kr/mod/assign/view.php?id=300106) until this week. 

Thanks

**Comment by oxsignal** [comment]
Plus, we are going to have a checkpoint meeting next week, so please upload the slides of it on [KLMS](http://klms.kaist.ac.kr/mod/assign/view.php?id=300123) as well.

**Comment by sangkilc** [comment]
You can upload your slides after the checkpoint meeting.

**Comment by oxsignal** [comment]
Please upload your slides on  [KLMS](http://klms.kaist.ac.kr/mod/assign/view.php?id=300123) until Today. Thanks

**Comment by oxsignal** [comment]
All slides are uploaded. One of our instructors will score your presentation done today. Thanks.
