### ISSUE TITLE
CA요구사항 관련

### ISSUE THREAD

**Issue by Hwi-gyeom** [KAIST-IS521/2019-Spring#27]
CA요구사항 중

 user should be able to upload their PGP key. If there is already an existing one, the uploaded one will replace the old one.

라는 문구가 있는데요,

유저가 다른key를 올린다면 아예 바꿔버리는게 맞는데,

유저가 A에게 사인받은 pgp key를 올렸는데 원래 db에는 B에게 사인받은 pgp key가 있다면 A,B 모두에게 사인받은 키를 저장할지, 그냥 유저가 새로올린거만 저장할지 불분명한 부분이 있는것 같습니다.

어떤식으로 하면 될까요?

**Comment by sangkilc** [comment]
There are two options to handle this:
1) You can just replace it with a new one.
2) You can merge those two keys, and update the current one.

Both options are fine. It is your decision decision. 1) is easier, but 2) can bring you more opportunity for inserting your back door.

**Comment by Hwi-gyeom** [comment]
답변감사합니다. 팀원들과 회의해보겠습니다.
