### ISSUE TITLE
CA certificate관련 문의

### ISSUE THREAD

**Issue by Hwi-gyeom** [KAIST-IS521/2019-Spring#29]
CA 만들던 중 의문이 생겨 질문을 드립니다.

CA certificate에는 다음과 같은 요구조건이 있습니다.

A registered (and authenticated) user should be able to download a certificate from the service, which basically contains the user's key signed by the CA service and the information about the user. You can create your own format or use an existing certificate format such as PKCS. However, it would be easier to create your own format for the purpose of this activity.

여기서 CA가 제공하는 certificate에 포함되는 user's key부분에 CA의 키로 사인한 키가 들어가야 할까요?

아니면 certificate에 따로 있는 인증으로 충분하기에 user's key에 CA의 사인은 필요없나요?

**Comment by Hwi-gyeom** [comment]
질문이 조금 불명확한거 같아서 다시 질문드립니다.

CA가 제공하는 certificate의 sign 이라는 것이 gpg가 import할 수 있는 key에 사인을 한 (gpg --sign-key 명령어) 것인지

user의 key를 데이터로보고 거기에 전자서명을 한 것인지 (gpg --sign 명령어)

혹은 아무거나해도 상관없는 것인지가 궁금합니다.

**Comment by sangkilc** [comment]
I believe both ways are fine.
