### ISSUE TITLE
Activity1 컴파일 및 실행환경 명시

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2019-Spring#3]
수강생 분들은 각 repo의 README.md에

과제에 이용한 언어의 버전과 컴파일/실행환경,
그리고 추가로 이용한 라이브러리가 있다면 그 라이브러리의 이름 및 설치 방법등을
명시해주시기 바랍니다.

위 사항들이 명확하지 않을 경우 원활한 과제 채점에 어려움이 있을 수 있으니
꼭 적어주세요.

**Comment by goguma-chsong** [comment]
안녕하세요 조교님. 정보보호 실습 수강생 송창훈입니다.
이 메일을 이제야 확인해서 뒤늦게 README.md를 약간 수정했지만 태그를 수정하지 못했습니다.. ㅠㅠ

일단 수정해서 다시 태그 올리도록 하겠습니다.

송창훈 올림.

보낸 사람: Minjoon Park
보낸 날짜: 2019년 3월 7일 목요일 오후 9:56
받는 사람: KAIST-IS521/2019-Spring
참조: Subscribed
제목: [KAIST-IS521/2019-Spring] Activity1 컴파일 및 실행환경 명시 (#3)

수강생 분들은 각 repo의 README.md에
과제에 이용한 언어의 버전과 컴파일/실행환경,
그리고 추가로 이용한 라이브러리가 있다면 그 라이브러리의 이름 및 설치 방법등을
명시해주시기 바랍니다.
위 사항들이 명확하지 않을 경우 원활한 과제 채점에 어려움이 있을 수 있으니
꼭 적어주세요.

**Comment by dinggul** [comment]
> 
> 안녕하세요 조교님. 정보보호 실습 수강생 송창훈입니다. 이 메일을 이제야 확인해서 뒤늦게 README.md를 약간 수정했지만 태그를 수정하지 못했습니다.. ㅠㅠ 일단 수정해서 다시 태그 올리도록 하겠습니다. 송창훈 올림. 보낸 사람: Minjoon Park 보낸 날짜: 2019년 3월 7일 목요일 오후 9:56 받는 사람: KAIST-IS521/2019-Spring 참조: Subscribed 제목: [KAIST-IS521/2019-Spring] Activity1 컴파일 및 실행환경 명시 (#3) 수강생 분들은 각 repo의 README.md에 과제에 이용한 언어의 버전과 컴파일/실행환경, 그리고 추가로 이용한 라이브러리가 있다면 그 라이브러리의 이름 및 설치 방법등을 명시해주시기 바랍니다. 위 사항들이 명확하지 않을 경우 원활한 과제 채점에 어려움이 있을 수 있으니 꼭 적어주세요. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

코드에 변경점이 없다면 바꾸지 않아도 괜찮습니다.

**Comment by dinggul** [comment]
Activity1 is ended
