### ISSUE TITLE
Team Group Activity Submission

### ISSUE THREAD

**Issue by oxsignal** [KAIST-IS521/2019-Spring#34]
As we are going to get to the  [Code auditing phase](https://github.com/KAIST-IS521/2019-Spring/blob/master/Activities/0319.md#code-auditing) on 4/30, each team should submit their project on their new repository, which named as ```2019s-gitctf-'Teamname'``` until 4/29, at noon.

I just finished inviting each student as a collaborator to each team repository, please accept the invitation. 

For convenience, you may use [Download zip](https://stackoverflow.com/a/2751270) option on your submission.

**Comment by dohki** [comment]
I didn't get invitation.

**Comment by oxsignal** [comment]
I just checked the repository, but it says still waiting for your response. 

Anyway, I will mail you personally with an invitation link.

**Comment by cshwan78** [comment]
Where should we upload our source codes? gitctf repo or KLMS?
It is confusing because [Preparation Activity](https://github.com/KAIST-IS521/2019-Spring/blob/master/Activities/0430.md#preparation) says that we have to submit it to KLMS.

**Comment by sangkilc** [comment]
Use KLMS and do not touch your repo yet.

**Comment by cshwan78** [comment]
There is no assignment on KLMS now. Please make new assignment. @oxsignal , @dinggul.
