### ISSUE TITLE
3rdparty 팀의 키가 새로 업데이트 되었습니다.

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2019-Spring#39]
#37 에서 공지되었던 문제가 해결되어 현재 이 repo의 TeamKey폴더에 3rdparty팀의 새 pubkey가 업로드 되었습니다.

각 팀은 새로 업데이트 된 키를 **반드시** 확인하고, 현재 저장해 놓은 과거의 키가 있다면 삭제하여
CTF에 지장이 없도록 준비해 주시기 바랍니다.

이 공지는 반드시 모든 학생이 빠르게 숙지해야 하는 관계로 9명의 학생이 이 공지에 확인했다는 댓글을 남기지 전 까지는  close되지 않습니다.

**Comment by dinggul** [comment]
이 공지에 댓글을 남기지 않은 팀원을 확인했다면, 빠르게 전달하여 내용 공유가 이루어 질 수 있기를 바랍니다.

**Comment by dohki** [comment]
확인하였습니다.

**Comment by euihyun-lee** [comment]
확인했습니다.

**Comment by KSAlpha** [comment]
확인했습니다

**Comment by cshwan78** [comment]
확인했습니다

**Comment by ymlee815** [comment]
확인하였습니다

**Comment by goguma-chsong** [comment]
확인하였습니다

**Comment by supersourbeam** [comment]
확인했습니다

**Comment by Hwi-gyeom** [comment]
확인했습니다

**Comment by coacerbet** [comment]
확인했습니다

**Comment by dinggul** [comment]
9명의 수강생 모두 해당 공지를 숙지했다는 것을 확인했습니다.
이제 3팀에게 찾은 버그를 issue해도 괜찮습니다.

행운을 빕니다.
