### ISSUE TITLE
Backdoor Patch

### ISSUE THREAD

**Issue by dohki** [KAIST-IS521/2019-Spring#51]
> You should upload two patches to your own git repository as two separate branches. ( [Reference](https://github.com/KAIST-IS521/2019-Spring/blob/master/Activities/0516.md#final-deliverables) )

Which repo do you mean by `your own git repository`?
1. https://github.com/KAIST-IS521/2019s-3rdparty
2. https://github.com/KAIST-IS521/2019s-gitctf-3rdparty

**Comment by dinggul** [comment]
1번입니다.
