### ISSUE TITLE
PGP Activity

### ISSUE THREAD

**Issue by dinggul** [KAIST-IS521/2019-Spring#6]
수강생 분들의 이메일로 TA들의 PGP 공개키를 발송하였습니다.

확인하신 후에, Activity의 지침에 따라 답장 부탁드립니다.

**Comment by dinggul** [comment]
TA가 서명된 pgp키를 받게되면 확인 메일을 드리도록 하겠습니다.

**Comment by sangkilc** [comment]
If you are using GPG2 (not GPG1), you may get into a trouble drawing a graph with sig2dot. If so, use the following command:
```gpg --list-sigs --keyid-format 0xLONG | perl sig2dot.pl > graph.dot```

**Comment by dinggul** [comment]
gmail로 메일을 받으시는 수강생 분들은 메일이 스팸메일함으로 들어가지 않았나 확인 바랍니다.
