### ISSUE TITLE
PGP Activity Repository

### ISSUE THREAD

**Issue by goguma-chsong** [KAIST-IS521/2019-Spring#7]
I would like to submit PGP activity in my personal repository, but I couldn't get the link yet.
Could you make it for us??

Thank you.

**Comment by dinggul** [comment]
personal repository 가 정확히 무엇을 의미하는 것 인지 잘 모르겠습니다.
activity의 제출을 위한 repo를 의미하는 것이라면, 이번 activity는 사전에 공지 되었던 대로 ([0314.md](https://github.com/KAIST-IS521/2019-Spring/blob/master/Activities/0314.md)) PR을 통해 제출하여야 합니다.

이외에 TA의 pgp key를 sign하는 과제의 경우에는 메일로 답장을 보내주시면 됩니다.

추가로 의문사항이 있으면 말씀 바랍니다.

**Comment by sangkilc** [comment]
I sent an email to everyone.

**Comment by dinggul** [comment]
아 제가 잘못 알았네요.. ㅠㅠ 죄송합니다

**Comment by goguma-chsong** [comment]
A digitally signed copy of the Ethical Conduct Agreement form. Use your PGP key and copy both the agreement form and the signature file to your own repository. You should follow the instruction there, i.e., you need to modify the agreement accordingly.

에 있는 것으로 보아 Agreement.md 를 sign해서 올렸어야 했는데 끝난 것 같군요,

감사합니다.
