### ISSUE TITLE
PGP activity repository permissions

### ISSUE THREAD

**Issue by KSAlpha** [KAIST-IS521/2019-Spring#9]
Hello,

I have created my repository (https://github.com/KAIST-IS521/pgp-KSAlpha) via GitHub Classroom, but I don't have a permission to push my commits.

I would like to have a write permission for my repository. I think other students are also encountering this problem.

Thanks a lot!

**Comment by sangkilc** [comment]
![Screenshot from 2019-03-18 14-32-29](https://user-images.githubusercontent.com/1836303/54508850-b905f280-498a-11e9-89dc-470a7c6987bd.png)

**Comment by sangkilc** [comment]
You have write permission, meaning that you can push things to the repository.

**Comment by KSAlpha** [comment]
I think I am having trouble with git configurations on my side. Thanks for your confirmation. :)
